JAVA_INC = "C:/Program Files/Java/jdk1.5.0_12/include"
FFTW_INC = "C:/Documents and Settings/mcallen/Desktop/fftw-3.1.2-dll/src/fftw-3.1.2/api"
FFTW_LIB = "c:/Documents and Settings/mcallen/Desktop/lunartuner"
CFLAGS = -Wall
INC = -I${JAVA_INC} -I${FFTW_INC}
LIB = -L${FFTW_LIB} -lfftw3-3 -lm

all:
	gcc ${CFLAGS} ${LIB} -D_JNI_IMPLEMENTATION_ -Wl,--kill-at -I${FFTW_INC} -I${JAVA_INC} -I${JAVA_INC}/win32 -shared Fftw.c -o fftw.dll
	