/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class misc_Fftw */

#ifndef _Included_misc_Fftw
#define _Included_misc_Fftw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     misc_Fftw
 * Method:    fft
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_misc_Fftw_fft
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
