package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.beans.*;
import java.net.*;
import pitchDetector.*;
import speech.*;
import misc.*;
import misc.InstrumentInfo.*;

public class LunarTunerGui extends javax.swing.JFrame {
	static private LunarTunerGui m_instance = new LunarTunerGui();
	static private ImageIcon m_icon = null;

	// For the interval notifier
	private boolean m_intervalEnabled = false;
	private long m_intervalLength;
	private long m_intervalLastNotification;
	
	private LunarTunerGui() {
		initComponents();
		loadInstruments();
		loadInstrumentNotes();
		
		ImageIcon img = new ImageIcon(getClass().getResource("/resource/icon.png"));
		setIconImage(img.getImage());
		m_intervalLength = 10000;
		m_intervalLastNotification = 0;
	}
	
	static public LunarTunerGui getInstance() {
		return m_instance;
	}
	
	static public void setPitchError(double err) {
		Graphics2D g = (Graphics2D)m_instance.m_lblMeter.getGraphics();
		ImageIcon icon = (ImageIcon)m_instance.m_lblMeter.getIcon();
		
		err = -1 * err;
		
		int errPix = icon.getIconHeight() / 2 + (int)err;
		if (errPix > icon.getIconHeight()) {
			errPix = icon.getIconHeight() - 1;
		}
		else
		if (errPix < 0) {
			errPix = 0;
		}
		
		g.drawImage(icon.getImage(), 0, 0, icon.getIconWidth(), icon.getIconHeight(), m_instance);
		g.setPaint(Color.RED);
		g.fillRect(0, errPix, icon.getIconWidth(), 3);
	}
	
	static public void setNoteHeard(String txt) {
		m_instance.m_txtNoteHeard.setText(txt);
	}
	
	static public void setInstructions(String txt) {
		m_instance.m_txtInstructions.setText(txt);
	}
	
	private void loadInstruments() {
		InstrumentInfo.Instrument[] inst = InstrumentInfo.getInstance().getInstruments();
		m_cbInstrumentType.addItem(new Instrument());
		for (int i = 0; i < inst.length; ++i) {
			m_cbInstrumentType.addItem(inst[i]);
		}
		
		m_cbInstrumentType.setSelectedIndex(0);
	}
	
	private void loadInstrumentNotes() {
		Instrument inst = (InstrumentInfo.Instrument)m_cbInstrumentType.getSelectedItem();
		InstrumentNote[] notes = inst.getNotes();
		m_cbInstrumentNote.removeAllItems();
		for (int i = 0; i < notes.length; ++i) {
			m_cbInstrumentNote.addItem(notes[i]);
		}
		
		if (notes.length > 0) {
			m_cbInstrumentNote.setSelectedIndex(0);
		}
	}
	
	private void resetIntervalTimer() {
		m_intervalLastNotification = new Date().getTime();
	}
	
   public static void updateIntervalTimer(String noteHeard, String noteError) {
		long now = new Date().getTime();
		if (now - m_instance.m_intervalLastNotification > m_instance.m_intervalLength 
				&& m_instance.m_intervalEnabled) {
			Speech.speak(noteHeard + " " + noteError);
			m_instance.m_intervalLastNotification = now;
		}
	}
	
	private void setIntervalNotifyLength(long interval) {
		m_intervalLength = interval;
	}
	
	private void setIntervalNotifyEnabled(boolean enabled) {
		m_intervalEnabled = enabled;
		m_intervalLastNotification = new Date().getTime();
	}
	
	public static void updateInterval(String noteHeard, String noteError, String noteInstructions) {
		long now = new Date().getTime();
		if (now - m_instance.m_intervalLastNotification > m_instance.m_intervalLength 
				&& m_instance.m_intervalEnabled) {			
			Speech.speak(noteInstructions);
			m_instance.m_intervalLastNotification = now;
		}
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      m_dlgAbout = new javax.swing.JDialog();
      jLabel6 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      m_dlgHelp = new javax.swing.JDialog();
      jLabel15 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      m_txtNoteHeard = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      m_txtInstructions = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      m_lblMeter = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      m_cbInstrumentType = new javax.swing.JComboBox();
      jLabel4 = new javax.swing.JLabel();
      m_cbInstrumentNote = new javax.swing.JComboBox();
      m_btnPlayNote = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      m_chkNotify = new javax.swing.JCheckBox();
      jLabel5 = new javax.swing.JLabel();
      m_cbNotifyInterval = new javax.swing.JComboBox();
      m_menuBar = new javax.swing.JMenuBar();
      m_menuFile = new javax.swing.JMenu();
      m_menuItemAbout = new javax.swing.JMenuItem();
      m_menuItemHelp = new javax.swing.JMenuItem();
      m_menuItemExit = new javax.swing.JMenuItem();

      m_dlgAbout.setLocationByPlatform(true);
      m_dlgAbout.setModal(true);
      m_dlgAbout.setResizable(false);
      jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.jpg")));

      jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel8.setText("Brought to you by Project Possibility");
      jLabel8.getAccessibleContext().setAccessibleDescription("");

      jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel9.setText("htp://www.projectpossibility.org");

      jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13));
      jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel10.setText("Developers");

      jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel11.setText("Marc Allen <allen.marc@gmail.com>");

      jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel12.setText("Chris Leung <christopher.leung@projectpossibility.org>");

      jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel13.setText("Please contact us with suggestions, features, and new accessible software project ideas!");

      jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel14.setText("To get involved or learn more about Project Possibility, please visit http://projectpossibility.org");

      jTextField1.setBackground(null);
      jTextField1.setEditable(false);
      jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 24));
      jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      jTextField1.setText("LunarTuner v0.1");
      jTextField1.setBorder(null);
      jTextField1.getAccessibleContext().setAccessibleName("LunarTuner v0.1\nBrought to you by Project Possibility\nhtp://www.projectpossibility.org\nDevelopers\nMarc Allen <allen.marc@gmail.com>\nChris Leung <christopher.leung@projectpossibility.org>\nPlease contact us with suggestions, features, and new accessible software project ideas!\nTo get involved or learn more about Project Possibility, please visit http://projectpossibility.org");
      jTextField1.getAccessibleContext().setAccessibleDescription("LunarTuner v0.1\nBrought to you by Project Possibility\nhtp://www.projectpossibility.org\nDevelopers\nMarc Allen <allen.marc@gmail.com>\nChris Leung <christopher.leung@projectpossibility.org>\nPlease contact us with suggestions, features, and new accessible software project ideas!\nTo get involved or learn more about Project Possibility, please visit http://projectpossibility.org");

      org.jdesktop.layout.GroupLayout m_dlgAboutLayout = new org.jdesktop.layout.GroupLayout(m_dlgAbout.getContentPane());
      m_dlgAbout.getContentPane().setLayout(m_dlgAboutLayout);
      m_dlgAboutLayout.setHorizontalGroup(
         m_dlgAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, m_dlgAboutLayout.createSequentialGroup()
            .addContainerGap()
            .add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
         .add(m_dlgAboutLayout.createSequentialGroup()
            .add(193, 193, 193)
            .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(202, 202, 202))
         .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
      );
      m_dlgAboutLayout.setVerticalGroup(
         m_dlgAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(m_dlgAboutLayout.createSequentialGroup()
            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel10)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel11)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel12)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel13)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel14)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      m_dlgHelp.setLocationByPlatform(true);
      m_dlgHelp.setModal(true);
      m_dlgHelp.setResizable(false);
      jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 24));
      jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel15.setText("LunarTuner Help");

      jTextArea1.setColumns(20);
      jTextArea1.setEditable(false);
      jTextArea1.setLineWrap(true);
      jTextArea1.setRows(5);
      jTextArea1.setText("LunarTuner is an accessible instrument tuning software, designed to be usable by the blind community.\n\nThere are two modes of operation: \"Automatic\" mode and \"Targeted  Note\" mode.  In Automatic mode, the tuner will find the closest note to  the pitch it detects and give determine the percent error based on that  note.  In Targeted Note mode, the user will select an instrument using  the \"Type\" dropdown menu and a note using the \"Note\" dropdown menu.   The tuner will then determine the percent error based on the target note,  and will use the \"Instructions\" field to tell the user whether to tune up or down.\n\nIn both modes, the \"Note Heard\" field will contain text regarding the  current note and error percentage.\n\nLunarTuner can also play a note on demand. If the user presses the \"Play Note\" button, the currently selected note will be played through the sound system.\n\nIf the user has a screen reader like Jaws and wants to be updated periodically with the current note, they can click the \"Enable Notify\" checkbox and set the \"Notify Interval in Seconds\" field to the desired update rate.  A dialog box containing the current note information will  be opened and closed at that interval to trigger to screen reader.  To stop the notifier, press the stop button in the dialog box or click  the \"Enable Notify\" checkbox again.\n\nLunarTuner requires Java 1.5+ and has been tested on Windows 2000/XP and Mac OS/X.");
      jTextArea1.setWrapStyleWord(true);
      jScrollPane1.setViewportView(jTextArea1);

      org.jdesktop.layout.GroupLayout m_dlgHelpLayout = new org.jdesktop.layout.GroupLayout(m_dlgHelp.getContentPane());
      m_dlgHelp.getContentPane().setLayout(m_dlgHelpLayout);
      m_dlgHelpLayout.setHorizontalGroup(
         m_dlgHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
         .add(m_dlgHelpLayout.createSequentialGroup()
            .add(24, 24, 24)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 568, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(20, 20, 20))
      );
      m_dlgHelpLayout.setVerticalGroup(
         m_dlgHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(m_dlgHelpLayout.createSequentialGroup()
            .add(jLabel15)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addContainerGap())
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setLocationByPlatform(true);
      setResizable(false);
      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Status")));
      jPanel1.setName("Status");
      jLabel1.setText("Note Heard");

      m_txtNoteHeard.setEditable(false);

      jLabel2.setText("Instructions");

      m_txtInstructions.setEditable(false);

      org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel1Layout.createSequentialGroup()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jLabel2)
               .add(jLabel1))
            .addContainerGap(178, Short.MAX_VALUE))
         .add(m_txtNoteHeard, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
         .add(m_txtInstructions, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel1Layout.createSequentialGroup()
            .add(jLabel1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(m_txtNoteHeard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLabel2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(m_txtInstructions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel1.getAccessibleContext().setAccessibleName("Status");

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
      m_lblMeter.setForeground(new java.awt.Color(255, 0, 0));
      m_lblMeter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/meter.gif")));

      org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(m_lblMeter)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(m_lblMeter)
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrument"));
      jLabel3.setText("Type");

      m_cbInstrumentType.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_cbInstrumentTypeActionPerformed(evt);
         }
      });

      jLabel4.setText("Note");

      m_cbInstrumentNote.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_cbInstrumentNoteActionPerformed(evt);
         }
      });

      m_btnPlayNote.setText("Play Note");
      m_btnPlayNote.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_btnPlayNoteActionPerformed(evt);
         }
      });

      org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel3Layout.createSequentialGroup()
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
               .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
               .add(m_cbInstrumentType, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .add(m_cbInstrumentNote, 0, 217, Short.MAX_VALUE)))
         .add(m_btnPlayNote)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel3Layout.createSequentialGroup()
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jLabel3)
               .add(m_cbInstrumentType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jLabel4)
               .add(m_cbInstrumentNote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(m_btnPlayNote))
      );

      jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Notify Settings"));
      m_chkNotify.setText("Enable Notify");
      m_chkNotify.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
      m_chkNotify.setMargin(new java.awt.Insets(0, 0, 0, 0));
      m_chkNotify.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_chkNotifyActionPerformed(evt);
         }
      });

      jLabel5.setText("Notify Interval in seconds");

      m_cbNotifyInterval.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
      m_cbNotifyInterval.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_cbNotifyIntervalActionPerformed(evt);
         }
      });

      org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel4Layout.createSequentialGroup()
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(m_chkNotify)
               .add(jPanel4Layout.createSequentialGroup()
                  .add(jLabel5)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(m_cbNotifyInterval, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(39, Short.MAX_VALUE))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel4Layout.createSequentialGroup()
            .add(m_chkNotify)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jLabel5)
               .add(m_cbNotifyInterval, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(26, Short.MAX_VALUE))
      );

      m_menuFile.setText("File");
      m_menuItemAbout.setText("About");
      m_menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_menuItemAboutActionPerformed(evt);
         }
      });

      m_menuFile.add(m_menuItemAbout);

      m_menuItemHelp.setText("Help");
      m_menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_menuItemHelpActionPerformed(evt);
         }
      });

      m_menuFile.add(m_menuItemHelp);

      m_menuItemExit.setText("Exit");
      m_menuItemExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            m_menuItemExitActionPerformed(evt);
         }
      });

      m_menuFile.add(m_menuItemExit);

      m_menuBar.add(m_menuFile);

      setJMenuBar(m_menuBar);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
               .add(jPanel1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
         .add(layout.createSequentialGroup()
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      pack();
   }// </editor-fold>//GEN-END:initComponents

	private void m_cbNotifyIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cbNotifyIntervalActionPerformed
		setIntervalNotifyLength(Long.parseLong((String)m_cbNotifyInterval.getSelectedItem()) * 1000);
	}//GEN-LAST:event_m_cbNotifyIntervalActionPerformed

	private void m_chkNotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_chkNotifyActionPerformed
		setIntervalNotifyLength(Long.parseLong((String)m_cbNotifyInterval.getSelectedItem()) * 1000);
		setIntervalNotifyEnabled(m_chkNotify.isSelected());
	}//GEN-LAST:event_m_chkNotifyActionPerformed

	private void m_menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_menuItemExitActionPerformed
		System.exit(0);
	}//GEN-LAST:event_m_menuItemExitActionPerformed

	private void m_menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_menuItemHelpActionPerformed
		m_dlgHelp.pack();
		m_dlgHelp.setVisible(true);
	}//GEN-LAST:event_m_menuItemHelpActionPerformed

	private void m_menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_menuItemAboutActionPerformed
		m_dlgAbout.pack();
		m_dlgAbout.setVisible(true);
	}//GEN-LAST:event_m_menuItemAboutActionPerformed
	
   private void m_cbInstrumentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cbInstrumentTypeActionPerformed
		loadInstrumentNotes();
   }//GEN-LAST:event_m_cbInstrumentTypeActionPerformed
	
   private void m_cbInstrumentNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cbInstrumentNoteActionPerformed
		String name = ((Instrument)m_cbInstrumentType.getSelectedItem()).getName();
		InstrumentNote note = (InstrumentNote)m_cbInstrumentNote.getSelectedItem();
		if (!name.equals("Automatic") && note != null) {
			UpdateLunarTuner.changeTuneNote(new PitchSample(note.getName(), note.getFreqIdx()));
		}
		else {
			UpdateLunarTuner.changeTuneNote(null);
		}
   }//GEN-LAST:event_m_cbInstrumentNoteActionPerformed
	
   private void m_btnPlayNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnPlayNoteActionPerformed
		InstrumentNote note = (InstrumentNote)m_cbInstrumentNote.getSelectedItem();
		if (note != null) {
			UpdateLunarTuner.playNote(new PitchSample(note.getName(), note.getFreqIdx()));
		}
   }//GEN-LAST:event_m_btnPlayNoteActionPerformed
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				LunarTunerGui.getInstance().setVisible(true);
			}
		});
		
		Thread updateThread = new Thread() {
			public void run() {
				UpdateLunarTuner.getInstance().updateLoop();
			}
		};

		Thread speechThread = new Thread() {
			public void run() {
				Speech.getInstance().updateLoop();
			}
		};
		
		updateThread.start();
		speechThread.start();
	}
	
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JButton m_btnPlayNote;
   private javax.swing.JComboBox m_cbInstrumentNote;
   private javax.swing.JComboBox m_cbInstrumentType;
   private javax.swing.JComboBox m_cbNotifyInterval;
   private javax.swing.JCheckBox m_chkNotify;
   private javax.swing.JDialog m_dlgAbout;
   private javax.swing.JDialog m_dlgHelp;
   private javax.swing.JLabel m_lblMeter;
   private javax.swing.JMenuBar m_menuBar;
   private javax.swing.JMenu m_menuFile;
   private javax.swing.JMenuItem m_menuItemAbout;
   private javax.swing.JMenuItem m_menuItemExit;
   private javax.swing.JMenuItem m_menuItemHelp;
   private javax.swing.JTextField m_txtInstructions;
   private javax.swing.JTextField m_txtNoteHeard;
   // End of variables declaration//GEN-END:variables
	
}
